// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240424161532_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API.Entities.CartItem", b =>
                {
                    b.Property<string>("KrepselioSkelbimoNr")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Kiekis")
                        .HasColumnType("int");

                    b.Property<string>("KrepselioNr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SkelbimoNr")
                        .HasColumnType("int");

                    b.Property<DateTime>("SukurimoData")
                        .HasColumnType("datetime(6)");

                    b.HasKey("KrepselioSkelbimoNr");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("API.Entities.Poster", b =>
                {
                    b.Property<int>("SkelbimoNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SkelbimoNr"));

                    b.Property<string>("Aprasas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GyvunuKategorija")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Ivertinimas")
                        .HasColumnType("int");

                    b.Property<float>("Kaina")
                        .HasColumnType("float");

                    b.Property<string>("Nuotrauka")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SkelbimoValidacija")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SkelbimoNr");

                    b.ToTable("Posters");
                });

            modelBuilder.Entity("API.Entities.Product", b =>
                {
                    b.Property<int>("ProduktoNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProduktoNr"));

                    b.Property<string>("Kategorija")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Kiekis")
                        .HasColumnType("int");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tiekejas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProduktoNr");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
